KAU2024-SANHAK/SANHAK_Client

.eslintrc.cjs, .prettierrc, package.json, yarn.lock
- close : #7 
- eslint 설치
- prettier 설치
- eslint 규칙 코드 작성
- prettier 코드 작성
- 일단 지금은 제가 해왔던 규칙 대로 적용 시켜 두었어요 !! 코드 작성하면서 불편하다 싶으면 이슈 하나 파서 수정해보도록 하겠습니다 !
=> [chore] eslint / prettier setting

.husky/_/husky.sh
- 정상적으로 작동되지 않는 것을 확인 하고, husky.sh 파일 내용을 수정하였습니다.
=> [fix] husky 파일 수정 

src/components/OnBoardingSteps/OnBoardingStep5/OnBoardingStep5.jsx, src/components/SetDiaryStyle/SetDiaryStyle.jsx, src/hooks/diary/useHandelDiaryType.jsx, src/hooks/queries/onboarding/usePostDiaryType.jsx, src/pages/MyPage/MyPagePopUp/MyPagePopUp.jsx, src/recoil/atoms.js
- close : #71 
- usePostDiaryType 을 통하여 handlePostDiaryType을 컴포넌트 내부에 구현하여 api 연결을 시도하였습니다.
- useHandleDiaryType은 구현만 해둔 상태이고, 주석처리 해두었습니다. 불필요할시 삭제 후 merge 하겠습니다.
- hooks는 나중에 다시 설정하도록 하겠습니다....어렵네요 ㅠㅠ
=> [feat] diaryType 설정 api 연결

src/components/CreatedDiary/CreatedDiary.jsx, src/components/FastDiarySteps/FastDiaryStep6.jsx, src/components/common/HoneyBear/FeelingHoneyBear.jsx, src/pages/DiaryView/DiaryView.jsx, src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.style.js, src/pages/EmotionView/EmotionView.jsx, src/utils/convertFeelingText.js
- close : #93 
- 빠른 일기 날짜 파싱
- 빠른 일기 감정 분석 페이지 제대로 이동
- 감정 분석 로딩 추가
- 빠른 일기 None일시, 느린 일기에서 감정 생성 
- 조언창 margin으로 변경하여 버튼 잘 눌리게 수정
- 
=> [refactor] 중간 발표 전 최종 리팩토링

src/components/CreatedDiary/CreatedDiary.jsx, src/components/FastDiarySteps/FastDiaryStep6.jsx, src/components/common/HoneyBear/FeelingHoneyBear.jsx, src/pages/DiaryView/DiaryView.jsx, src/pages/DiaryView/DiaryViewPopUp/DiaryViewPopUp.style.js, src/pages/EmotionView/EmotionView.jsx, src/utils/convertFeelingText.js
* feat: 감정 분석시 로딩창 띄우기
- 내가 뭘했는지
=> Develop에서 Main merge (중간 발표 최종 리팩토링)

src/components/MainStep/MainStep2/MainStep2.jsx, src/components/common/Calendar/Calendar.jsx, src/components/common/Calendar/Calendar.style.js, src/pages/DiaryList/DiaryList.sytle.js
- close : #[94] 달력 컴포넌트 / 일기 리스트 사진 포함
- 달력 컴포넌트 로직 수정 및 메인화면 일기 리스트 띄워줄 때 사진 포함
=> [refactor] #94 달력 컴포넌트 및 일기 리스트 사진 포함하도록 수정

src/components/KakaoAd/KakaoAd.jsx, src/components/KakaoAd/KakaoAd.style.js, src/components/KakaoAd/KakaoAdCallback.jsx, src/components/MainStep/MainStep1/MainStep1.jsx
- close : #107 
- kakao ad 에서 320에 50 사이즈의 배너 광고를 등록 후, useEffect와 useRef를 활용하여 Main step1 에 해당 광고 배너를 위치 시켜놓았습니다.
- figma 디자인과 비교하여 약간은 위쪽에 위치 시켰는데, main page의 스타일 코드를 재 수정하기에 어려움을 느껴 그렇게 했습니다 ! 현재 화면은 밑에 첨부한 화면과 같으며, 해당 부분에 대한 스타일 변경이 필요하다면, main 페이지 담당 소민님께서 요청해 주셨을때 수정 변경 하겠습니다!
- 추가적으로 추후 광고가 잘 적용 되는지 배포 페이지에서 확인이 필요할 거 같아, 빠른 main merge 가 필요할 거 같습니다 !
=> [feat] 광고 시스템 삽입

index.html
- close : #115 
- google analytics 계정을 생성하고 head에 해당 코드를 삽입하였습니다.
=> [feat] head에 ga 코드 삽입

src/components/CreatedDiary/CreatedDiary.jsx, src/components/CreatedDiary/CreatedDiary.style.js, src/components/Modal/Modal.style.js, src/components/Modal/OptionModal.jsx, src/components/common/buttons/Menu/Menu.jsx, src/components/common/buttons/Menu/Menu.style.js, src/components/common/buttons/Share/Share.jsx, src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.style.js, src/pages/DiaryView/DiaryView.jsx, src/pages/DiaryView/DiaryView.style.js, src/pages/FastDiary/FastDiary.jsx, src/pages/MyPage/MyPage.style.js, src/pages/SearchByEmotion/SearchByEmotion.style.js, src/pages/SlowDiary/SlowDiary.jsx
- close : #117 
- 기존 HomeModal을 OptionModal로 바꾸어 기존 모달창에서 재사용성을 늘렸습니다.
- 일기 삭제시 모달창을 띄웁니다.
- 메인 화면 SummaryHoneyBear 컴포넌트를 모든 화면에서 위치를 동일하게 유지하도록 수정하였습니다.  
- 아침에 확인하시면 머지 진행하겠습니다! 혹시 제가 늦게 일어난다면.... merge 진행해주시면 감사하겠습니다../.!
=> [feat] 일기 삭제시 모달창 띄우기

src/components/FastDiarySteps/FastDiaryStep.style.js, src/components/MainStep/MainStep1/MainStep1.style.js, src/components/MainStep/MainStep2/MainStep2.style.js, src/components/common/buttons/MyPageButton/MyPageButton.jsx, src/components/common/buttons/MyPageButton/MyPageButton.style.js, src/components/common/buttons/SearchByEmotionButton/SearchByEmotionButton.jsx, src/components/common/buttons/SearchByEmotionButton/SearchByEmotionButton.style.js, src/pages/FastDiary/FastDiary.jsx, src/pages/FastDiary/FastDiary.style.js, src/pages/Main/Main.jsx, src/pages/Main/Main.style.js
- close : #125 
- 배포페이지에서 absolute를 활용해 깨지는 부분에 대해서 수정했습니다.
- main step1 에서 마이페이지로 이동하는 버튼과 감정별 리스트 버튼 스타일 수정했습니다.
- main step1,2에서 honeybear wrapper에 height를 줬습니다.
- fast diary 의 absoulte 부분에 height와 width를 주고 최대한 flex와 margin padding gap을 활용하여 수정했습니다.
- 배포페이지에서 확인 다시 해보면 좋을 거 같습니다 ! merge 하고 !
=> [refactor] 배포페이지에서 absolute를 활용해 깨지는 부분에 대해서 수정

src/pages/DiaryView/DiaryView.jsx, src/pages/Loading/Loading.jsx, src/pages/Loading/Loading.style.js
- close : #130 
- postMutation 오타 수정하여 조언이 생성 및 로딩창이 잘 보이도록 수정
- 로딩창 width 값을 37.5rem으로 조절
=> [refactor] 조언 오타 수정 및 로딩창 width 조정

src/hooks/queries/create/usePostAiImage.jsx
- close : #132 
- ai 이미지 생성을 백엔드와 연결하도록 수정하였습니다.
=> [feat] 백 서버와 ai이미지 생성 연결

package.json, src/components/MainStep/MainStep1/MainStep1.jsx, src/components/MainStep/MainStep1/MainStep1.style.js, src/components/MainStep/MainStep2/MainStep2.jsx, src/components/MainStep/MainStep2/MainStep2.style.js, src/components/common/Calendar/Calendar.jsx, src/components/common/DiaryListComponent/DiaryListComponent.jsx, src/components/common/buttons/EmotionType/EmotionType.jsx, src/pages/Main/Main.jsx, src/pages/Main/Main.style.js, yarn.lock
- close : #[120] 버튼에 에니메이션 적용
- 내가 뭘했는지
=> #120 버튼에 에니메이션 적용

src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.jsx, src/hooks/queries/create/usePostAdvice.jsx, src/hooks/queries/main/usePostPlaylist.jsx
- close : #133 
- 유튜브 플레이 리스트 api 연결 구현
- response 값과 window 객체를 통하여 해당 플레이리스트 링크로 이동하도록 구현
=> [feat]유튜브 플레이리스트 api 연결 

src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.jsx, src/hooks/queries/create/usePostAdvice.jsx, src/hooks/queries/main/usePostPlaylist.jsx
=> Develop에서 main merge(유튜브 플리)

src/components/CreatedDiary/CreatedDiary.jsx, src/components/CreatedDiary/CreatedDiary.style.js, src/components/MainStep/MainStep2/MainStep2.jsx, src/components/common/DiaryListComponent/DiaryListComponent.jsx, src/pages/DiaryList/DiaryList.jsx, src/pages/SearchByEmotion/SearchByEmotionPopUp/SearchByEmotionPopUp.jsx
- close : #142 
- 모달 컴포넌트 정리
- 감정 생성 불가 모달 구현
- 리스트에서 따옴표 파싱
- 유튜브 플리 response 값 오타 수정
=> [feat] 감정 생성 불가 에러 모달 및 따옴표 파싱

src/apis/client.js, src/components/CreatedDiary/CreatedDiary.jsx, src/components/common/buttons/Share/Share.jsx, src/hooks/queries/etc/useGetSharedDiary.jsx, src/pages/DiaryView/DiaryView.jsx, src/pages/SharedView/SharedView.jsx, src/pages/SharedView/SharedView.style.js, src/recoil/atoms.js, src/router/Router.jsx, src/utils/shareKakao.js
- close : #123 
- get method를 통한 일기 내용들 api로 받아오는 코드 작성
-  flex와 padding 값들 위주로 스타일 코드 작성
- 날짜, 따옴표 파싱 및 개행 처리 완료 
- 감사합니다...
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
https://github.com/KAU2024-SANHAK/SANHAK_Client/assets/104068583/b1a0e211-f30f-487f-b772-836a25917a86
=> [feat]카카오 공유하기 구현

src/apis/client.js, src/components/CreatedDiary/CreatedDiary.jsx, src/components/CreatedDiary/CreatedDiary.style.js, src/components/MainStep/MainStep1/MainStep1.jsx, src/components/MainStep/MainStep1/MainStep1.style.js, src/components/MainStep/MainStep2/MainStep2.jsx, src/components/OnBoardingSteps/OnBoardingStep.style.js, src/components/OnBoardingSteps/title/Title.style.js, src/components/common/DiaryListComponent/DiaryListComponent.jsx, src/components/common/HoneyBear/HoneyBear.jsx, src/components/common/buttons/Share/Share.jsx, src/components/common/buttons/ThisMonthEmotion/ThisMonthEmotion.jsx, src/hooks/queries/create/usePostAdvice.jsx, src/hooks/queries/etc/useGetSharedDiary.jsx, src/hooks/queries/main/usePostPlaylist.jsx, src/hooks/useMobile.jsx, src/pages/DiaryList/DiaryList.jsx, src/pages/DiaryView/DiaryView.jsx, src/pages/FastDiary/FastDiary.jsx, src/pages/FastDiary/FastDiary.style.js, src/pages/Main/Main.jsx, src/pages/Main/Main.style.js, src/pages/SearchByEmotion/SearchByEmotionPopUp/SearchByEmotionPopUp.jsx, src/pages/SharedView/SharedView.jsx, src/pages/SharedView/SharedView.style.js, src/pages/Start/Start.jsx, src/recoil/atoms.js, src/router/Router.jsx, src/utils/shareKakao.js
=> Develop에서 main merge (style 수정 및 카카오 공유하기)

src/hooks/queries/fastdiary/usePostKeywords.jsx
=> [refacto] usePosyKeyword 헤더 직접 설정

src/pages/MyPage/MyPage.jsx, src/pages/MyPage/MyPage.style.js, src/pages/SearchByEmotion/SearchByEmotion.jsx, src/pages/SearchByEmotion/SearchByEmotion.style.js
- close : #[160]
- 페이지 두개 반응형으로 수정했어요!
=> [refactor] 마이페이지와 감정별 일기 조회하기 페이지 반응형으로 수정

src/components/MainStep/MainStep1/MainStep1.jsx, src/pages/Weather/Weather.jsx, src/pages/Weather/Weather.style.js, src/router/Router.jsx
=> [refactor] 임시 라우트에 날씨 api 적용

src/pages/Start/Start.jsx, src/pages/Start/Start.style.js
- close : #[182] start 페이지에 허니어리란? 버튼 추가하여 허니어리 인포 볼 수 있도록 하기
- 내가 뭘했는지
=> [refactor] #182 start 페이지에 허니어리란? 버튼 추가하여 허니어리 인포 볼 수 있도록 하기

src/components/CreatedDiary/CreatedDiary.jsx, src/pages/DiaryView/DiaryView.jsx, src/pages/Loading/Loading.style.js
- close : #184 
- 조언과 이미지가 안 보이면 새로고침을 하라는 문구 추가
- ai 로딩 컴포넌트 position 값 수정 
-
=> [refactor] 로딩 컴포넌트 position 값 및 텍스트 수정

src/components/OnBoardingSteps/OnBoardingStep.style.js, src/components/OnBoardingSteps/OnBoardingStep5.jsx, src/components/OnBoardingSteps/title/Caption.jsx, src/components/OnBoardingSteps/title/Title.style.js
- close : #189 
- 온보딩 step5 width 32rem 수정
=> [refactor] 온보딜 step5 컴포넌트 및 캡션 width값, margin값 수정

src/components/common/buttons/Menu/Menu.style.js
=> [style] 일기 수정하기 및 삭제하기 버튼 스타일

src/components/common/buttons/Menu/Menu.style.js
- close : #[197] 메뉴 스타일 수정
- 내가 뭘했는지
죄송합니다.. 제가 빡대가리라.. 디벨롭 반영되었는지 확인도 안하고 머지해서 반영이 안되었습니다.. 바로 메인머지하겠습니다..
=> style: 메뉴 스타일 수정 (이전 디벨롭에서 충돌 잘못해결해서 반영안됨 -> 다시 메인머지하기 위함)

README.md, src/components/common/buttons/Menu/Menu.style.js
- close : Develop에서 main merge
- 내가 뭘했는지
=> Develop에서 main merge

src/components/common/buttons/Menu/Menu.style.js
=> [refactor] 메뉴 스타일 수정

src/styles/GlobalStyle.js
=> refactor: 폰트 default 설정

src/hooks/common/useFileReader.jsx, src/pages/SlowDiary/DiaryForm/DiaryForm.jsx, src/pages/SlowDiary/DiaryForm/DiaryForm.style.js, src/pages/SlowDiary/SlowDiary.jsx, src/pages/SlowDiary/SlowDiary.style.js, src/styles/theme.js
- close : #217 
- 공통된 style 코드를 css 함수로 처리
- theme font에 속성값으로 lettering-space 추가
- 들여쓰기, 세미콜론 수정
- 필요없는 함수 삭제(blob 변환, 따옴표 파싱)
- 변수명 수정 
- 오랜만이네요 ㅎㅎ 앞으로 페이지 하나씩 고쳐나갈 예정입니다 !!
늘 그랬듯 아쉬운 부분들 적어주시면 바로바로 반영하겠습니다
다들 방학도 화이팅 ~
=> [refactor] 느린 일기 페이지 리팩토링

src/apis/client.js, src/pages/FallbackUI/FallbackUI.jsx, src/pages/FallbackUI/FallbackUI.style.js, src/pages/LoginError/LoginError.jsx, src/pages/LoginError/LoginError.style.js, src/pages/MyPage/MyPagePopUp/MyPagePopUp.jsx, src/router/Router.jsx
- close : #221
- 로그인이 되어 있지 않은 상태로 ai나 api서버로 api 요청을 하게 되면 null 값이 전달되며 적절하게 db 저장이 되지 않기 때문에 해당 부분을 사용자에게 노티 주기 위한 LoginError 페이지를 interceptor를 활용하여 추가해두었습니다.
https://github.com/user-attachments/assets/53f23fbc-0703-48ea-afcc-61be7785e3b0
=> [feat] 로그인 안 하고 url 이동 방지
